### ISSUE TITLE
weekly goal item diffs pathway

### ISSUE THREAD

**Issue by davidtlee** [tech4good-lab/causeway-examples#16]

**Comment by audsostrom** [comment]
Based off of yesterday's meeting, I figured I'd hold off on creating the files and formal pull requests for each diff. What I've instead done for now is I've put all of the phases of the diff guide (i.e. static, data, layout, etc.) into markdown files that can easily be transferred over.

**Comment by davidtlee** [comment]
@audsostrom my impression is that this has been finished. if so, you can mark this as closed (I don't think this requires any merging in since we're keeping the diffs in commits).

but also, can you add a comment in this issue with links to each commit in the diff pathway? (so it'll be easy to find in the future if needed just by looking for the issue)
